# Generated by Django 4.2.19 on 2025-02-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_course_user_teacher_poll_learner_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='enrolled_courses',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Learner',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
